#!/bin/bash -e

use_4100=0
if [ "$1" == "4100" ]
then
use_4100=1
fi

SCRIPT_DIR=`pwd`

# Take version
MAJOR=`grep "#define XN_PS_MAJOR_VERSION" ../../../Include/XnPsVersion.h | awk '{ print $3 }' | strings -n 1`
MINOR=`grep "#define XN_PS_MINOR_VERSION" ../../../Include/XnPsVersion.h | awk '{ print $3 }' | strings -n 1`
MAINTENANCE=`grep "#define XN_PS_MAINTENANCE_VERSION" ../../../Include/XnPsVersion.h | awk '{ print $3 }' | strings -n 1`
BUILD=`grep "#define XN_PS_BUILD_VERSION" ../../../Include/XnPsVersion.h | awk '{ print $3 }' | strings -n 1`

PS_VERSION="$MAJOR.$MINOR.$MAINTENANCE.$BUILD"

# clean
rm -rf Final
rm -rf ../Redist

# Build Engine
if [ "$use_4100" == "1" ]
then
cd ../Build
./Make.4100
cd -
else
make -C ../Build
fi

# create redist folder structure
mkdir -p ../Redist
mkdir -p ../Redist/Lib
mkdir -p ../Redist/Bin
mkdir -p ../Redist/Install
mkdir -p ../Redist/Config

# copy files to redist
cp ../../../GPL.txt ../Redist
cp ../../../LGPL.txt ../Redist
cp ../Bin/Release/libXnDeviceSensorV2.* ../Redist/Lib
cp ../Bin/Release/libXnDeviceFile.* ../Redist/Lib
cp ../Bin/Release/libXnDDK.* ../Redist/Lib
cp ../Bin/Release/libXnFormats.* ../Redist/Lib
cp ../Bin/Release/libXnCore.* ../Redist/Lib
cp ../Bin/Release/XnSensorServer ../Redist/Bin
cp ../Install/* ../Redist/Install
cp ../../../Data/GlobalDefaults.ini ../Redist/Config
cp install.sh ../Redist

# create tar
mkdir -p Final
cd ../Redist

if [ "`uname -s`" == "Darwin" ]; then
	TAR_TARGET="MacOSX"
elif [ "$use_4100" == "1" ]; then
	TAR_TARGET="CE4100"
elif [ "`uname -m`" == "i686" ]; then
	TAR_TARGET="Linux32"
elif [ "`uname -m`" == "x86_64" ]; then
	TAR_TARGET="Linux64"
else
	TAR_TARGET="Linux"
fi

tar -cjf $SCRIPT_DIR/Final/Sensor-Bin-$TAR_TARGET-v$PS_VERSION.tar.bz2 *

cd -
